# https://prettier.io/docs/en/options

useTabs: false
tabWidth: 4
printWidth: 80
semi: true
singleQuote: true
quoteProps: consistent
jsxSingleQuote: true
trailingComma: all
bracketSpacing: true
bracketSameLine: true
arrowParens: always
proseWrap: preserve
htmlWhitespaceSensitivity: css
vueIndentScriptAndStyle: true
endOfLine: lf
embeddedLanguageFormatting: auto
singleAttributePerLine: false